### ISSUE TITLE
KeyError: 'result'  to get info

### ISSUE THREAD

**Issue by aetherwu** [jihao/colorfulclouds-hass#2]
2019-08-03 14:19:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 254, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/colorfulclouds/weather.py", line 74, in state
    skycon = self._realtime_data['result']['realtime']['skycon']
KeyError: 'result'

**Comment by 0uzu0** [comment]
> 2019-08-03 14:19:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 254, in async_update_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in _async_write_ha_state
> state = self.state
> File "/config/custom_components/colorfulclouds/weather.py", line 74, in state
> skycon = self._realtime_data['result']['realtime']['skycon']
> KeyError: 'result'

检查你的经纬度和api_key设置，这是数据没有获取到
